# This file was generated by backpackR

library(RPostgres)
library(divDB)
library(backpackR)

# start-dontrun ----------------------------------------------------------------
setwd("lab/project-2")
conn <- connect_db(dbname = "test-db")

#build_db(path = "../", dbname = "test-db", overwrite = TRUE, wd = tempdir())
#release_project(".", "../")
# end-dontrun ------------------------------------------------------------------

# Write new table
dbWriteTable(conn, c("data_frames", "trees"), trees)
