# This file was generated by backpackR

library(RPostgres)
library(backpackR)
library(biblioDB)

# start-dontrun ****************************************************************
setwd("lab/exp-references/project-1")
conn <- divDB::connect_db(dbname = "mreferences")

## Bib <- read_bib("../all-references.bib")[1:100, ]
## write_bib(Bib, "references.bib")

# end-dontrun ******************************************************************

Bib <- read_bib("references.bib")

dbSendQuery(conn, "drop schema if exists bibliorefs")

bib2database(conn, schema = "bibliorefs", bib = Bib)

## dbGetQuery(conn, paste("select count(*)", "from bibliorefs.main_table"))
## release_project(project = "../project-1", path = "../")
