# This file was generated by backpackR

library(RPostgres)
library(divDB)
library(backpackR)
library(biblioDB)

# start-dontrun ****************************************************************
setwd("lab/exp-references/project-3")
conn <- divDB::connect_db(dbname = "mreferences")

## Bib <- read_bib("../all-references.bib")
## write_bib(Bib, "references.bib")

# end-dontrun ******************************************************************

Bib <- read_bib("references.bib")

compare_df(conn, Bib, schema = "bibliorefs")

update_data(conn, Bib, schema = "bibliorefs", add = TRUE)

## dbGetQuery(conn, paste("select count(*)", "from bibliorefs.main_table"))
## release_project(project = "../project-3", path = "../")
