database: test-db
user: miguel
initialized: 2024-01-03 00:03
dms: PostgreSQL 16.1 (Ubuntu 16.1-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled
  by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
server: 16.1 (Ubuntu 16.1-1.pgdg22.04+1)
remarks: |
  Initial update for the schema data_frames in test-db.
released: 2024-01-03 23:44
