# This file was generated by backpackR

# Import required packages
library(backpackR)
library(biblioDB)

# Set working directory
setwd("lab/references/project-1")

# Connect database
conn <- connect_db(dbname="references-db", port="5433")

# Read database
Bib <- read_bib("references-miguel.bib")

# Import library to database
dbSendQuery(conn, "drop schema if exists refs cascade")
bib2database(conn, "refs", Bib)
