database: references-db
user: miguel
initialized: 2023-12-31 00:55
dms: PostgreSQL 16.1 (Ubuntu 16.1-1.pgdg22.04+1) on x86_64-pc-linux-gnu, compiled
  by gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0, 64-bit
server: 16.1 (Ubuntu 16.1-1.pgdg22.04+1)
